export interface Transaction {
	accounts: ​​number,
	changeInCoins: number,
	date: string,
	id: number,
	max_balance: number,
	richest: string,
	shift: number,
	top_10_accounts: number,
	top_10_ownership: number,
	top_10_wealth: number,
	top_25_accounts: number,
	top_25_ownership: number,
	top_25_wealth: number,
	top_50_accounts: number,
	top_50_ownership: number,
	top_50_wealth: number,
	top_5_accounts: number,
	top_5_ownership: number,
	top_5_wealth: number,
	total: number,
}
